# Generated by Django 2.2.3 on 2019-08-02 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=60, null=True)),
                ('type', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=11)),
                ('storage_conditions', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sum_of_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(max_length=30)),
                ('miesiac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=128)),
                ('tekst_poczatek', models.CharField(blank=True, max_length=128, null=True)),
                ('tekst_koniec', models.CharField(blank=True, max_length=128, null=True)),
                ('raport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sekcje', to='Arctowski_app.Raport')),
                ('sekcjaNadzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podSekcje', to='Arctowski_app.Sekcja')),
            ],
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=128)),
                ('sekcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy', to='Arctowski_app.Sekcja')),
            ],
        ),
        migrations.CreateModel(
            name='InCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=12)),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=11)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arctowski_app.Case')),
            ],
        ),
    ]
