# Generated by Django 2.2.3 on 2019-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='hight',
            new_name='height',
        ),
        migrations.AddField(
            model_name='case',
            name='capacity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=11),
        ),
    ]
