# Generated by Django 2.2.3 on 2019-07-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0002_auto_20190731_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='capacity',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
