# Generated by Django 2.2.3 on 2019-08-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0004_auto_20190731_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.CharField(max_length=30)),
                ('miesiac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sekcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=128)),
                ('tekst_poczatek', models.CharField(blank=True, max_length=128, null=True)),
                ('tekst_koniec', models.CharField(blank=True, max_length=128, null=True)),
                ('raport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sekcje', to='Arctowski_app.Raport')),
                ('sekcjaNadzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podSekcje', to='Arctowski_app.Sekcja')),
            ],
        ),
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=128)),
                ('sekcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wpisy', to='Arctowski_app.Sekcja')),
            ],
        ),
    ]
