# Generated by Django 2.2.3 on 2019-08-08 14:46

import Arctowski_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0006_auto_20190801_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Arctowski_app.models.Photo.group_based_upload_to),
        ),
        migrations.AlterField(
            model_name='photo',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to=Arctowski_app.models.Photo.group_based_upload_to),
        ),
    ]
