# Generated by Django 2.2.3 on 2019-08-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0006_auto_20190801_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
