# Generated by Django 2.2.3 on 2019-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0006_auto_20190801_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='storage_conditions',
            field=models.CharField(choices=[('pokład', 'pokład'), ('ładownia', 'ładownia'), ('kabina', 'kabina'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
