# Generated by Django 2.2.3 on 2019-08-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0007_auto_20190808_1446'),
        ('Arctowski_app', '0007_auto_20190808_2201'),
    ]

    operations = [
    ]
