# Generated by Django 2.2.3 on 2019-08-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0007_auto_20190804_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='owner_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='case',
            name='storage_conditions',
            field=models.CharField(choices=[('pokład', 'pokład'), ('ładownia', 'ładownia'), ('kabina', 'kabina'), ('+4', '+4'), ('-20', '-20'), ('-80', '-80')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=11),
        ),
        migrations.AlterField(
            model_name='case',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='incase',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='incase',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Arctowski_app.Case'),
        ),
        migrations.AlterField(
            model_name='incase',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incase',
            name='unit_of_measurement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incase',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
