# Generated by Django 2.2.3 on 2019-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0008_auto_20190804_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incase',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='incase',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incase',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
