# Generated by Django 2.2.3 on 2019-08-05 20:30

import Arctowski_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arctowski_app', '0010_auto_20190804_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=Arctowski_app.models.Photo.fileLocation)),
                ('scan', models.FileField(null=True, upload_to=Arctowski_app.models.Photo.fileLocation)),
                ('photo_case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Arctowski_app.Case')),
            ],
        ),
    ]
